### PR TITLE
Added Armored Scout Gestuchar

### PR DESCRIPTION
**Pull request by Zayberex**
+ArmoredScoutGestuchar
+updated repo

### CODE REVIEW

**Comment by sindreslungaard** [comment]
I think this will work but might become a problem later if there are any cards that want to do something if you have any creatures with PowerAttacker or DoubleBreaker as this implementation will not give the PowerAttacker condition at all and DoubleBreaker only when they attack.

A more futureproof solution would be to use the PersistentEffect system to make sure the card always has those two conditions whenever there are no other fire creatures in the zone.

Something like:
```go
c.Use(fx.When(fx.Summoned, func(card *match.Card, ctx *match.Context) {
	// When summoned, make a persistent effect that runs the code inside for every event until exit() is called
	ctx.Match.ApplyPersistentEffect(func(ctx2 *match.Context, exit func()) {
		// Remove the conditions and exit the persistent effect when the card is no longer in the battle zone
		if card.Zone != match.BATTLEZONE {
			card.RemoveConditionBySource(card.ID)
			exit()
			return
		}

		// Whenever a card is moved while the persistent effect is active, remove the conditions
		// and add them back only if there are no other fire creatures in the battle zone
		if _, ok := ctx2.Event.(*match.CardMoved); ok {
			card.RemoveConditionBySource(card.ID)

			fireCreatures := fx.FindFilter(
				c.Player,
				match.BATTLEZONE,
				func(card *match.Card) bool { return c.Civ == civ.Fire }
			)

			if len(fireCreatures) == 1 {
				card.AddUniqueSourceCondition(cnd.PowerAttacker, 3000)
				card.AddUniqueSourceCondition(cnd.DoubleBreaker, true)
			}	
		}
	})
}))
```

**Comment by Zayberex** [comment]
> I think this will work but might become a problem later if there are any cards that want to do something if you have any creatures with PowerAttacker or DoubleBreaker as this implementation will not give the PowerAttacker condition at all and DoubleBreaker only when they attack.
> 
> A more futureproof solution would be to use the PersistentEffect system to make sure the card always has those two conditions whenever there are no other fire creatures in the zone.
> 
> Something like:
> 
> ```go
> c.Use(fx.When(fx.Summoned, func(card *match.Card, ctx *match.Context) {
> 	// When summoned, make a persistent effect that runs the code inside for every event until exit() is called
> 	ctx.Match.ApplyPersistentEffect(func(ctx2 *match.Context, exit func()) {
> 		// Remove the conditions and exit the persistent effect when the card is no longer in the battle zone
> 		if card.Zone != match.BATTLEZONE {
> 			card.RemoveConditionBySource(card.ID)
> 			exit()
> 			return
> 		}
> 
> 		// Whenever a card is moved while the persistent effect is active, remove the conditions
> 		// and add them back only if there are no other fire creatures in the battle zone
> 		if _, ok := ctx2.Event.(*match.CardMoved); ok {
> 			card.RemoveConditionBySource(card.ID)
> 
> 			fireCreatures := fx.FindFilter(
> 				c.Player,
> 				match.BATTLEZONE,
> 				func(card *match.Card) bool { return c.Civ == civ.Fire }
> 			)
> 
> 			if len(fireCreatures) == 1 {
> 				card.AddUniqueSourceCondition(cnd.PowerAttacker, 3000)
> 				card.AddUniqueSourceCondition(cnd.DoubleBreaker, true)
> 			}	
> 		}
> 	})
> }))
> ```

For some reason you can't play this card, or charge mana with it using that code xD

**Comment by Zayberex** [comment]
clideo_editor_2bacea3ae4784b2f8e2b64e388f98810

**Comment by sindreslungaard** [comment]
added in #237

**Pull request closed without merging**
