### PR TITLE
feat: SinisterGeneralDamudo

### PR DESCRIPTION
**Pull request by fabianTMC**
feat: Added Text to a Card to eventually make it searchable as well.

### CODE REVIEW

**Comment by fabianTMC** [comment]
Card image will have to be replaced because I am unable to access octgn as I am not using Windows

**Comment by sindreslungaard** [comment]
All card images for dm05 is already in the webapp, for Sinister the ID is f66ca3b3-7300-41ef-8319-9de6dfc4e39a. I'll add all the images for dm06 to the repo when dm05 is complete.

For searchable card text in the future we can use OCTGN's database for that as well since we already are using their card ids. So that could all be done frontend

**Comment by fabianTMC** [comment]
I have fixed the ID issue. I think I missed it while searching through the cards somehow.

For card text, we could also have it used for other purposes in the future. If it's a deal breaker to keep, we can remove it but it would be easier to have in our repo IMO.

**Comment by sindreslungaard** [comment]
I think even if we want to have it in the backend it would probably still end up being added as a separate lookup unless someone wants to go back and add it to all the cards that has already been implemented. Otherwise those future features would only have support for half of all the cards in the tcg. Could probably be automated a bit for existing cards, but why not just use a full database that already exists and also has more data like rarity, card number in the set etc - also slightly less work when adding new cards 😅

**Comment by fabianTMC** [comment]
I'm not averse to adding to whatever cards we have at the moment. That would take a bit of time though. So probably by the time we finish rolling out DM-06, it could all be up. 

The reason I think it would be better if we have it in our cards, or even as a lookup, is that it will make it easier to build the user profile and any stats stuff that we want. 

The lookup would work as well. I think I am just put off by external sources dependencies :sweat_smile: 

Either way I will follow your lead since I only just started contributing, so if you are firm with the no, I'll remove the text and push.

**Comment by sindreslungaard** [comment]
I think we should do without for now, and if we want to add it to the cards along the way maybe do that in a separate branch and merge when we actually have most of them done or add a feature that uses it. I'm a bit afraid we start adding texts and then it never gets finished for all the cards and end up being dead code 😅 

Another minor point towards using an external lookup instead would be that all the texts are duplicated throughout all cards (even copies of same card) in every match as the cards do not have a concept of static variables and were only meant to have data that might change on a per-card level (even copies) during a match

**Comment by fabianTMC** [comment]
Makes sense. I have removed it

**Pull request merged**
