### PR TITLE
Added Q-tronic Gargantua

### PR DESCRIPTION
**Pull request by Zayberex**
+QTronicGargantua
+updated repo

### CODE REVIEW

**Comment by sindreslungaard** [comment]
I think both options would work fine, but it should probably add the condition as a "UniqueSourceCondition" so that it doesn't remove the ShieldBreakModifier conditions applied by other cards.

Also it looks like this will only apply the effect to this specific card and not other survivors in the battle zone. Might need to listen for all attack creature/player events and check if the attacking card is a survivor and not the opponent's card.

**Comment by Zayberex** [comment]
Well, it should apply the effect only to that card cause Crew Breaker isn’t supposed to be shared with other survivors

**Comment by sindreslungaard** [comment]
Ah, didn't know about that ruling. Maybe only change to using UniqueSourceCondition then?

**Comment by sindreslungaard** [comment]
The RemoveCondition function will also have to be updated to RemoveConditionBySource to work properly with the latest commit

**Pull request merged**
