### PR TITLE
WIP: Client Improvements

### PR DESCRIPTION
**Pull request by severinkaderli**
This WIP for now. More detailed description will come later.

This PR is aiming at cleaning up the components and splitting the code base into multiple components. I also working on redoing pages using CSS grids and I want to move all dialogs to use vue-js-modal to be consistent. Tons of other changes as well like CSS variables. The design will stay almost exactly the same.

Will work on this over the next week or so.

If there are any current suggestions that I could implement I'm open for comments.

Changes:
* General
  * Use CSS variables
  * Load config into Vue.$config
* Components
  * BaseLink
    * A wrapper around the standard a element with some stylings.
  * ExternalLink
    * Links heading to external sites. These set the `rel` attribute to `noopener` and `noreferrer` for security reasons.
  * ButtonLink
    * Links that look like buttons
* Overview
  * Make layout using CSS Grid
  * Make it more responsive
  * Move Header, UserList, Chat and DuelList to separate components
  * Create component for new duel dialog
  * Create component for error dialogs
* Header
  * Use proper router-links for navigation instead of $router.push()
  * Use BaseLink and ExternalLink components for links
* Deck Editor
  * Move CardList to separete component

### CODE REVIEW

**Comment by sindreslungaard** [comment]
Awesome work 👍

Some frontend suggestions based on feedback I have seen throughout the lifespan of the site:

- It should be possible to open the "preview card" popup from any card image on the site, including modals.
- Hovering over card names in the deck builder should show a not-too-large preview of the card.
- It should be possible to see the total amount of cards you have in your deck in the deck builder.
- When selecting e.g. "Burning Mane" in the left side of the deck builder, if you have a "Burning Mane" in the deck already, that should also be selected, letting you use both the arrow buttons.
- Amount of cards in a players hand should be visible.
- When creating a new match, the Name input should be prefilled with what you last used (stored in localStorage maybe?)
- It should be possible to filter cards in the deck builder on the family of a card. All spells could go under a family called "Spells".

**Comment by sindreslungaard** [comment]
Also, I think a big goal for this project should be to make it easy to use on mobile. It' already possible to play on mobile as almost everything scales to the vertical height of the screen, but it could definitely be improved.

**Comment by severinkaderli** [comment]
Coming along nicely with the work on the overview page. It now uses CSS Grid for the layout and adapts better to smaller screens:

Tablet:
localhost_8080_overview

Mobile:
localhost_8080_overview (1)

I also changed the new duel dialog to use vue-js-modal:
image

**Comment by severinkaderli** [comment]
Finally I've got some time again to continue work on the frontend. I just started with the deck editor.

For now I moved to card list to a separate component and added a grid view-mode to it. The old list / table view is
also available.

image

**Comment by sindreslungaard** [comment]
Looks great! Really looking forward to when this is ready to be merged 🙂

**Comment by severinkaderli** [comment]
I might have some time in the near future to work on this again. It's long overdue :stuck_out_tongue:

**Comment by sindreslungaard** [comment]
awesome! i'll be setting some time off to add new cards and fix issues soon too

**Comment by severinkaderli** [comment]
I finally manged to get some work done on this. The deck editor should now be functional. Would be great if someone could take a look at the interface and give some feedback.

**Comment by severinkaderli** [comment]
Done some more work on this. I finally migrated the client to Vue 3 and fixed a bunch of formatting issues.

**Comment by Fightlapa** [comment]
Hi. What's the current state of that? A lot of work was done here, it would be so nice it could be used somehow. Can it be finished without introducing more functionality? Just to make use what was already done.

**Comment by fabianTMC** [comment]
@Fightlapa could we not pull the current work, test if it works and go from there?

@severinkaderli's profile says he does not use Github anymore

**Comment by severinkaderli** [comment]
You're free to use and modify the code here. I just don't have the time to work on this :(.

**Pull request closed without merging**
