### PR TITLE
First batch of files for DM06

### PR DESCRIPTION
**Pull request by Zayberex**

### CODE REVIEW

**Comment by sindreslungaard** [comment]
Hey, nice PR. Some feedback:

- Card-specific logic should not be mixed into the core of the codebase or in generic components, i.e. code specifically for the card CocoLupia should not exist in player.go or creature.go. And conditions in general should be generic, not for a single card (cnd.ReduceCostLupia)
- Indentation of a lot of the code is out of place, I recommend to enable formatting on save. Golang comes with a formatter.
- I assume this is not intentional
  ```
  if condition.ID == cnd.ReducedCostLupia {
          if condition.ID == cnd.ReducedCostLupia {
  ```
- Should not use `ctx.InterruptFlow()` for events that are not specifically for that card unless we wan't to cancel the whole event. You use it several places to cancel the EndOfTurn event which will break other cards that wants to do stuff during that event
- The change in `game/cards/dm02/dark_lord.go` was probably not meant to be part of this PR
- The commented out sections of imports at the top of some files should be removed. A formatter would do that automatically for you
- Currently the PR does not compile because there are some unused imports in certain files
- None of the new cards from this PR has been added to the `repository.go` file
- Not a big deal but I suggest using `fx.Select` over `match.Search` to prompt the user to select cards. Both works for this case but select is what we typically use for newer cards as it has more utility than the search and since we recommend new contributors to look at newer cards as reference for how to implement cards it would be good that we use the most up to date functions for it. match.Search is mostly used in dm01 and dm02 before select was created to take its place. I.e.
    ```go
    fx.Select(
        card.Player,
        ctx.Match,
        card.Player,
        match.BATTLEZONE,
        "Select one of your creatures that will be destroyed",
        1,
        1,
        false,
    ).Map(func(x *match.Card) {
        ctx.Match.Destroy(x, card, match.DestroyedByMiscAbility)
    })
    ```

**Comment by Zayberex** [comment]
```
if condition.ID == cnd.ReducedCostLupia {
        if condition.ID == cnd.ReducedCostLupia {
```
was based on

```
	manaCost := card.ManaCost
	for _, condition := range card.Conditions() {
		if condition.ID == cnd.ReducedCost {
			if condition.ID == cnd.ReducedCost {
				manaCost -= condition.Val.(int)
				if manaCost < 1 {
					manaCost = 1
				}
			}
```

and as it is written in the repo commit description, every card from dm06 is added there, but the creatures that are being tested need to be uncommented. If I did commit a file without comments for unused cards,  the console would tell that they are undefined.
And as I am not really "in programming", I don't actually know that the thing called _formatter_ exists, or how do I use it.

**Comment by sindreslungaard** [comment]
Yeah you are right, the double check for ReducedCost should also not be there 😅

>  every card from dm06 is added there, but the creatures that are being tested need to be uncommented. If I did commit a file without comments for unused cards, the console would tell that they are undefined.

I don't mean to uncomment all the cards from dm06, just the ones you added in this PR, otherwise how will they be playable?

> And as I am not really "in programming", I don't actually know that the thing called formatter exists, or how do I use it.

Well this is very impressive if you're not into programming! If you use vscode make sure you have the official [Go extension](https://marketplace.visualstudio.com/items?itemName=golang.Go) installed, I believe this comes with format on save out of the box. If not it can be changed in the settings of your editor. To format a file manually in vscode you can use `shift + alt + f`

**Comment by Zayberex** [comment]
Well, I'm using Brackets, my 3GB free hard drive doesn't allow VS :cry:

**Comment by sindreslungaard** [comment]
drawing

**Comment by fabianTMC** [comment]
I think Sindre meant Visual Studio Code not Visual Studio the full IDE. It is much smaller.

https://code.visualstudio.com/

**Review by Zayberex — COMMENTED** [review]
Wrong commit for ArcBinetheAstounding, card's tap ability doesn't work for other light creatures

**Comment by sindreslungaard** [comment]
Hey,

I think we can move forward with this in two ways. Either keep adding cards and functionality to this pull request and let me know when it is ready to be reviewed, then I can review everything at once when it's all done and you're happy with it. Alternatively I can start reviewing this pull request now and you can open a new pull requests for any new cards/functionality that is not included in this one.

For the future it would make the process of getting these cards merged much quicker if we split up into multiple pull requests with a couple of new cards per. That way an issue with 1 card does not block the other 50 from being released.

**Comment by Zayberex** [comment]
You can start reviewing it now and I will add next cards when i learn how to make separate pr

**Comment by sindreslungaard** [comment]
I have skimmed through the changes here and see some cards that are not working or has unintended side-effects that might not have been obvious while creating or testing them. I think it would be easiest if we close this PR and split it up into smaller ones (maybe 5-10 cards or a couple of races per) so that I can review and provide feedback on them individually while merging the ones that are ok and working. Otherwise I predict this PR will be alive for a long time and a few difficult cards will block the rest of them from being released.

I created a separate PR for the first batch of commits in this PR here https://github.com/sindreslungaard/duel-masters/pull/153 and merged it already.

Would that be ok for you? Splitting up PR's are not the easiest thing to do unless you're a git magician so I would recommend simply forking the current master branch and creating separate branches per PR you want to make. So for example create a branch from master and apply the changes for 5-10 cards and create a pull request for that, then a new branch from master again and apply the changes for 5-10 other cards. This can be done either using [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) or simply copying the code over from this PR manually after creating the new branch.

You also have me on discord so feel free to message me if you need assistance with that! I don't want to make it more difficult, but at the same time I don't want to jump in and hijack the whole PR with changes and fixes so splitting it up into smaller issues seems like a reasonable approach.

**Pull request closed without merging**
